services:
  winet-extractor:
    restart: unless-stopped
    image: ghcr.io/marvambass/winet-extractor:latest
    build:
      context: .
    volumes:
      - ./env:/usr/src/app/.env:ro
    network_mode: host
    environment:
      - TZ=Europe/Berlin
